source "https://rubygems.org"
gem "jekyll"#, "~> 4.2.2"
group :jekyll_plugins do
  gem "jekyll-feed"#, "~> 0.12"
  gem "jekyll-seo-tag"#, "~> 2.6"
end

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
platforms :mingw, :x64_mingw, :mswin, :jruby do
  #gem "tzinfo"#, "~> 1.2"
  #gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", :platforms => [:mingw, :x64_mingw, :mswin]

gem "http_parser.rb"

gem "webrick"#, "~> 1.7"

gem "sass-embedded"#, "~> 1.62"
